version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and start container
          command: docker-compose up -d
      
      - run:
          name: Run tests - Pytest
          command: |
            docker exec -it wtdpy bash -c "python setup.py test"
            docker cp wtdpy:/wtdpy/htmlcov /tmp/artifacts

      - run:
          name: Build docs
          command: |
            docker exec -it wtdpy bash -c "pip install sphinx"
            docker exec -it wtdpy bash -c "python setup.py docs"
            docker cp wtdpy:/wtdpy/docs/_build/html /tmp/artifacts/docs
      
      - run:
          name: Post to Coveralls
          command: |
            docker exec -it wtdpy bash -c "pip install coveralls"
            docker exec -it wtdpy bash -c "coveralls"
      
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/